RedHatInsights/ccx-notification-service:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/gotests.yaml.tmpl
    dest: .github/workflows/gotests.yaml
    template:
      coverage_threshold: 67
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd.yaml
    template:
      service: notification-service
      extra_options:
        use_kafka: true
        use_postgres: true

RedHatInsights/ccx-notification-writer:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/gotests.yaml.tmpl
    dest: .github/workflows/gotests.yaml
    template:
      coverage_threshold: 62
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd.yaml
    template:
      service: notification-writer
      extra_options:
        use_postgres: true

RedHatInsights/ccx-upgrades-data-eng:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/pytests.yaml
    dest: .github/workflows/pytests.yaml
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd.yaml
    template:
      service: data-engineering-service
      extra_options:
        use_mock-oauth2-server: true

RedHatInsights/ccx-upgrades-inference:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/pytests.yaml
    dest: .github/workflows/pytests.yaml
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd.yaml
    template:
      service: inference-service

RedHatInsights/content-service:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/gotests.yaml.tmpl
    dest: .github/workflows/gotests.yaml
    template:
      coverage_threshold: 67
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd.yaml
    template:
      service: content-service

RedHatInsights/data-pipeline:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-ccx-messaging:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/pytests.yaml
    dest: .github/workflows/pytests.yaml

RedHatInsights/insights-content-template-renderer:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/pytests.yaml
    dest: .github/workflows/pytests.yaml
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd.yaml
    template:
      service: content-template-renderer

RedHatInsights/insights-core-messaging:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/pytests.yaml
    dest: .github/workflows/pytests.yaml

# RedHatInsights/insights-data-schemas:
#   - CODEOWNERS

RedHatInsights/insights-on-prem:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-operator-gathering-conditions:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-operator-gathering-conditions-service:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/gotests.yaml.tmpl
    dest: .github/workflows/gotests.yaml
    template:
      coverage_threshold: 85

RedHatInsights/insights-operator-utils:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/gotests.yaml.tmpl
    dest: .github/workflows/gotests.yaml
    template:
      coverage_threshold: 69

RedHatInsights/insights-results-aggregator:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd-aggregator.yaml
    template:
      service: aggregator
      extra_options:
        use_kafka: true
        use_postgres: true
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd-dvo.yaml
    template:
      service: dvo-writer
      extra_options:
        use_kafka: true
        use_postgres: true

RedHatInsights/insights-results-aggregator-cleaner:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/gotests.yaml.tmpl
    dest: .github/workflows/gotests.yaml
    template:
      coverage_threshold: 84
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd.yaml
    template:
      service: cleaner
      extra_options:
        use_postgres: true

# RedHatInsights/insights-results-aggregator-data:
#   - CODEOWNERS

RedHatInsights/insights-results-aggregator-exporter:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/gotests.yaml.tmpl
    dest: .github/workflows/gotests.yaml
    template:
      coverage_threshold: 59
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd.yaml
    template:
      service: exporter
      extra_options:
        use_postgres: true
        use_minio: true

RedHatInsights/insights-results-aggregator-mock:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/gotests.yaml.tmpl
    dest: .github/workflows/gotests.yaml
    template: {}
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd.yaml
    template:
      service: aggregator-mock

RedHatInsights/insights-results-aggregator-utils:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

# RedHatInsights/insights-results-mcp:
#   - CODEOWNERS

RedHatInsights/insights-results-smart-proxy:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/gotests.yaml.tmpl
    dest: .github/workflows/gotests.yaml
    template:
      coverage_threshold: 72
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd.yaml
    template:
      service: smart-proxy

RedHatInsights/obsint-mocks:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/parquet-factory:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/gotests.yaml.tmpl
    dest: .github/workflows/gotests.yaml
    template:
      coverage_threshold: 72
  - source: workflows_examples/bdd.yaml.tmpl
    dest: .github/workflows/bdd.yaml
    template:
      service: parquet-factory
      extra_options:
        use_kafka: true
        use_minio: true
        use_pushgateway: true

RedHatInsights/insights-behavioral-spec:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
  - source: workflows_examples/pytests.yaml
    dest: .github/workflows/pytests.yaml
