name: Update Jira-Glitchtip Integration Data

on:
  schedule:
    - cron: '0 4 * * *'  # daily at 4AM UTC
  workflow_dispatch:     # allow manual execution

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: true
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          cd jira-glitchtip-issues-closer
          pip install -r requirements.txt

      - name: Update README with integration data
        env:
          MAX_DAYS_OF_INACTIVITY: 7
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          GLITCHTIP_API_TOKEN: ${{ secrets.GLITCHTIP_API_TOKEN }}
        run: |
          cd jira-glitchtip-issues-closer
          python3 main.py > README.md

      - id: app_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.OBSINT_PROCESSING_APP_CLIENT_ID }}
          private-key: ${{ secrets.OBSINT_PROCESSING_APP_PRIVATE_KEY }}
          owner: RedHatInsights

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.app_token.outputs.token }}
          sign-commits: true
          title: "chore: update Jira-Glitchtip integration data [bot]"
          body: "This PR is automatically created by the obsint-processing-app bot."
          branch: obsint-processing-app/jira-glitchtip-integration-data
          labels: "bot"
          commit-message: "chore: update Jira-Glitchtip integration data [bot]"
          committer: "obsint-processing-app[bot] <274936164+obsint-processing-app[bot]@users.noreply.github.com>"
          author: "obsint-processing-app[bot] <274936164+obsint-processing-app[bot]@users.noreply.github.com>"
          delete-branch: true
