name: Sync Files
on:
  pull_request:
  workflow_dispatch:

jobs:
  sync-test:
    runs-on: ubuntu-latest
    steps:
      - id: app_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.OBSINT_PROCESSING_APP_CLIENT_ID }}
          private-key: ${{ secrets.OBSINT_PROCESSING_APP_PRIVATE_KEY }}
          owner: RedHatInsights
